server:
  port: 80

spring:
  data:
    mongodb:
      host: ec-products-mongo
      port: 27018
      database: products
  application:
    name: ec-products-service
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka
  instance:
    preferIpAddress: true
    nonSecurePort: 80
